apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchmaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matchmaker
  template:
    metadata:
      generateName: "matchmaker-"
      labels:
        app: matchmaker
    spec:
      containers:
      - name: matchmaker
        image: matchmaker
        ports:
        - containerPort: 3001
        env:
          - name: APP_NAME
            value: "matchmaker"
          - name: SERVER_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.generateName
          - name: PORT
            value: "3001"
          - name: REDIS_STORE
            value: matchmaker-redis:6379
          - name: APP_SECRET
            valueFrom:
              secretKeyRef:
                name: vsnet
                key: appSecret