apiVersion: v1
kind: Service
metadata:
  name: matchmaker
  labels:
    app: matchmaker
spec:
  type: LoadBalancer
  selector:
    app: matchmaker
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 30001
    protocol: TCP