version: "3"
services:
  orchestrator:
    build:
      context: ./orchestrator
      dockerfile: Dockerfile.dev
    volumes:
      - ./orchestrator/app/src:/app/orchestrator/src
    depends_on:
      - orchestrator-redis-database
    expose:
      - 3000
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - PORT=3000
      - APP_SECRET=abcde12345
      - REDIS_DATABASE_URL=redis://orchestrator-redis-database:6379
      - HEALTHCHECK_INTERVAL=5000
      - HEALTHCHECK_START_DELAY=5000
      - HEALTHCHECK_MAX_RETRIES=3
    networks:
      - vsnet
  game:
    build:
      context: ./game
      dockerfile: Dockerfile.dev
    volumes:
      - ./game/app/src:/app/game/src
    expose:
      - 8080-8087
    ports:
      - 8080-8087
    depends_on:
      - game-redis-database
      - orchestrator
    environment:
      - NODE_ENV=development
      - PORT=8080
      - APP_SECRET=abcde12345
      - REDIS_DATABASE_URL=redis://game-redis-database:6379
      - ORCHESTRATOR_SERVICE_URL=http://orchestrator:3000
    networks:
      - vsnet
  social:
    build:
      context: ./social
      dockerfile: Dockerfile.dev
    volumes:
      - ./social/app/src:/app/social/src
    expose:
      - 3000
    ports:
      - 3001:3000
    depends_on:
      - social-redis-pubsub
    environment:
      - NODE_ENV=development
      - PORT=3000
      - APP_SECRET=abcde12345
      - REDIS_PUBSUB_URL=redis://social-redis-pubsub:6379
    networks:
      - vsnet
  matchmaker:
    build:
      context: ./matchmaker
      dockerfile: Dockerfile.dev
    volumes:
      - ./matchmaker/app/src:/app/matchmaker/src
    expose:
      - 3000
    ports:
      - 3002:3000
    depends_on:
      - matchmaker-redis-database
    environment:
      - NODE_ENV=development
      - PORT=3001
      - APP_SECRET=abcde12345
      - REDIS_DATABASE_URL=redis://matchmaker-redis-database:6379
    networks:
      - vsnet
  users:
    build:
      context: ./users
      dockerfile: Dockerfile.dev
    volumes:
      - ./users/app/src:/app/users/src
    expose:
      - 3000
    ports:
      - 3003:3000
    depends_on:
      - users-postgres
    environment:
      - NODE_ENV=development
      - PORT=3000
      - APP_SECRET=abcde12345
      - DATABASE_URL=postgres://vsnet@users-postgres/users
    networks:
      - vsnet
  orchestrator-redis-database:
    image: redis
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - vsnet
  game-redis-database:
    image: redis
    expose:
      - 6379
    ports:
      - 6380:6379
    networks:
      - vsnet
  social-redis-pubsub:
    image: redis
    expose:
      - 6379
    ports:
      - 6381:6379
    networks:
      - vsnet
  matchmaker-redis-database:
    image: redis
    expose:
      - 6379
    ports:
      - 6382:6379
    networks:
      - vsnet
  users-postgres:
    image: postgres:10.2-alpine
    environment:
      POSTGRES_USER: vsnet
      POSTGRES_DB: users
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - vsnet
networks:
  vsnet:
    driver: "bridge"