apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator-redis
  template:
    metadata:
      labels:
        app: orchestrator-redis
    spec:
      containers:
      - name: orchestrator-redis
        image: redis
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator-redis
  labels:
    app: orchestrator-redis
spec:
  type: ClusterIP
  selector:
    app: orchestrator-redis
  ports:
  - port: 6379
    targetPort: 6379