apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      generateName: "orchestrator-"
      labels:
        app: orchestrator
    spec:
      containers:
      - name: orchestrator
        image: orchestrator
        ports:
        - containerPort: 3001
        env:
          - name: APP_NAME
            value: "orchestrator"
          - name: SERVER_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.generateName
          - name: PORT
            value: "3001"
          - name: HEALTHCHECK_INTERVAL
            value: "5"
          - name: HEALTHCHECK_MAX_RETRIES
            value: "5"
          - name: REDIS_STORE
            value: orchestrator-redis:6379
          - name: APP_SECRET
            valueFrom:
              secretKeyRef:
                name: vsnet
                key: appSecret