apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  labels:
    app: orchestrator
spec:
  type: ClusterIP
  selector:
    app: orchestrator
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP