module.exports = {
  DEFAULT_HEALTHCHECK_INTERVAL: 5 * 1000,
  DEFAULT_HEALTHCHECK_MAX_RETRIES: 3,
  DEFAULT_HEALTHCHECK_START_DELAY: 5 * 1000,
  LOCK_RESOURCE_KEY: 'healthcheck',
  FAILED_HEALTHCHECK_COUNTER_KEY: 'failedHealthcheckCount',
  ACTIVE_CONNECTIONS_KEY: 'activeConnections',
  REGISTER_TIME_KEY: 'registerTime',
};
