apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
    protocol: TCP